name: Build and Test in dev-cloud

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:
    # Allows manual triggering of the workflow
    
permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f docker-requirements.txt ]; then pip install -r docker-requirements.txt; fi
        
    - name: Run static analysis
      run: |
        pip install pylint
        pylint --disable=C0111,C0103,C0303,C0301,W0511 src/ || true
        
    - name: Build Docker image
      run: |
        docker build -t redmine-mcp-server:${{ github.sha }} .
        
    - name: Save Docker image
      run: |
        docker save redmine-mcp-server:${{ github.sha }} > redmine-mcp-server-image.tar
        
    - name: Upload Docker image as artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: redmine-mcp-server-image.tar
        
  test:
    needs: build
    runs-on: ubuntu-latest
    environment: dev-cloud
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Download Docker image
      uses: actions/download-artifact@v4
      with:
        name: docker-image
        
    - name: Load Docker image
      run: |
        docker load < redmine-mcp-server-image.tar
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f docker-requirements.txt ]; then pip install -r docker-requirements.txt; fi
        
    - name: Install pytest and coverage
      run: |
        python -m pip install pytest pytest-cov

    - name: Run unit tests with coverage
      run: |
        echo "Running unit tests with coverage"
        pytest tests/ -v --cov=src --cov-report=xml --junitxml=test-results.xml || true
        
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          test-results.xml
          
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
        
    - name: Create PR for README badge update
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      env:
        REDMINE_URL: "https://redstone.redminecloud.net"
        REDMINE_API_KEY: ${{ secrets.REDMINE_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Creating PR to update README.md with test badge"
        
        # Create badge URL using shields.io
        BADGE_URL="https://img.shields.io/github/actions/workflow/status/${{ github.repository }}/build-and-test.yml?branch=main&label=tests&style=for-the-badge"
        
        # Create a new branch for the update
        BRANCH_NAME="update-test-badge-$(date +%s)"
        git checkout -b "$BRANCH_NAME"
        
        # Update README with badge
        if ! grep -q "<!-- test-status-badge -->" README.md; then
          # Add badge section if it doesn't exist
          sed -i '1 a\\n<!-- test-status-badge -->\\n[![Tests]('$BADGE_URL')](https://github.com/${{ github.repository }}/actions)\\n' README.md
        else
          # Update existing badge
          sed -i 's|<!-- test-status-badge -->.*|<!-- test-status-badge -->\\n[![Tests]('$BADGE_URL')](https://github.com/${{ github.repository }}/actions)|' README.md
        fi
        
        # Check if there are changes to commit
        if git diff --quiet README.md; then
          echo "No changes to README.md needed"
        else
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update test status badge in README"
          git push origin "$BRANCH_NAME"
          
          # Create pull request using GitHub CLI
          gh pr create \
            --title "Update test status badge" \
            --body "Automated update of test status badge in README.md" \
            --head "$BRANCH_NAME" \
            --base main
        fi
        
    - name: Run validation tests
      env:
        REDMINE_URL: "https://redstone.redminecloud.net"
        REDMINE_API_KEY: ${{ secrets.REDMINE_API_KEY }}
        TEST_PROJECT: "p1"
        SERVER_MODE: "test"
      run: |
        echo "Running validation tests against Redmine issues in v1 project"
        cd tests && python test_redstone.py
        
    - name: Run Docker container tests
      env:
        REDMINE_URL: "https://redstone.redminecloud.net"
        REDMINE_API_KEY: ${{ secrets.REDMINE_API_KEY }}
        TEST_PROJECT: "p1"
      run: |
        echo "Running Docker container tests in test mode"
        
        # Create a Dockerfile.test for running tests
        cat > Dockerfile.test << EOF
        FROM redmine-mcp-server:${{ github.sha }}
        ENV REDMINE_URL=$REDMINE_URL
        ENV REDMINE_API_KEY=$REDMINE_API_KEY
        ENV SERVER_MODE=test
        ENV TEST_PROJECT=$TEST_PROJECT
        CMD ["sh", "-c", "cd tests && python test_redstone.py"]
        EOF
        
        # Build the test container
        docker build -t redmine-mcp-server-test:${{ github.sha }} -f Dockerfile.test .
        
        # Run the container in test mode with the p1 project
        docker run --name redmine-test redmine-mcp-server-test:${{ github.sha }}
        
        # Get exit code from container
        EXIT_CODE=$?
        
        # Report result
        if [ "$EXIT_CODE" -eq "0" ]; then
          echo "Docker container tests passed"
        else
          echo "Docker container tests failed with exit code $EXIT_CODE"
          exit 1
        fi
        
  deploy:
    needs: test
    runs-on: ubuntu-latest
    environment: dev-cloud
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop')
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Download Docker image
      uses: actions/download-artifact@v4
      with:
        name: docker-image
        
    - name: Load Docker image
      run: |
        docker load < redmine-mcp-server-image.tar
        
    - name: Create GitHub Release
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        body: |
          Release v${{ github.run_number }} of Redmine MCP Server
          
          Build from commit: ${{ github.sha }}
          
          This release has been tested against the dev-cloud environment.
        draft: false
        prerelease: false
        
    - name: Update validation project with release info
      env:
        REDMINE_URL: "https://redstone.redminecloud.net"
        REDMINE_API_KEY: ${{ secrets.REDMINE_API_KEY }}
      run: |
        echo "Updating Redmine validation project with release information"
        python - <<EOF
        import os
        import sys
        import json
        import datetime
        # Make sure we can import from src
        sys.path.insert(0, os.path.abspath('.'))
        from src.redmine_client import RedmineClient
        
        # Get environment variables
        redmine_url = os.environ.get("REDMINE_URL")
        redmine_api_key = os.environ.get("REDMINE_API_KEY")
        
        if not redmine_url or not redmine_api_key:
            print("Redmine URL or API key not available")
            sys.exit(1)
            
        # Initialize API client
        client = RedmineClient(redmine_url, redmine_api_key)
        
        # Try to load validation issues
        if os.path.exists('validation_issues.json'):
            with open('validation_issues.json', 'r') as f:
                validation_data = json.load(f)
                
            master_issue_id = validation_data.get('master_issue_id')
            
            if master_issue_id:
                # Update master issue with release info
                timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                note = f"## Release Information\n\n"
                note += f"**Release**: v${{ github.run_number }}\n"
                note += f"**Timestamp**: {timestamp}\n"
                note += f"**Commit**: ${{ github.sha }}\n"
                note += f"**Branch**: ${{ github.ref }}\n\n"
                note += f"**Status**: Successfully deployed to dev-cloud environment\n"
                
                # Add note
                client.update_issue(master_issue_id, {"notes": note})
                print(f"Updated master validation issue #{master_issue_id} with release info")
        EOF
        
    # Publish to GitHub Packages if running on main or master branch
    - name: Publish Docker image to GitHub Packages
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: |
        # Login to GitHub Container Registry
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        
        # Tag the image for GitHub Container Registry
        docker tag redmine-mcp-server:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/redmine-mcp-server:latest
        docker tag redmine-mcp-server:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/redmine-mcp-server:v${{ github.run_number }}
        
        # Push the images
        docker push ghcr.io/${{ github.repository_owner }}/redmine-mcp-server:latest
        docker push ghcr.io/${{ github.repository_owner }}/redmine-mcp-server:v${{ github.run_number }}